name: SEN5EI
favicon: null
layout_spectrum: 0.6049262913875282
typography_spectrum: 0.8514629469718784
title: SEN5EI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8184530450962484
  lightness: 0.791201988235116
  saturation: 0.8026122418232262
  rhythmicContrast: 0.07642841851338744
purpose: []
